/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import static java.awt.Image.SCALE_DEFAULT;
import java.io.File;
import java.util.Arrays;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import model.Info;
import model.ProfileList;

/**
 *
 * @author ZeyuLiao
 */


public class CreatePanel extends javax.swing.JPanel {

    /**
     * Creates new form CreatePanel
     */
    
    ProfileList pList;
    //initialize wrong input flag
    int[] flag = {0,0,0,0,0,0,0,0};
    
    public CreatePanel(ProfileList pList) {
        this.pList = pList;
        initComponents();
        //hide wrong input notice
        jLabelNoticeName.setVisible(false);
        jLabelNoticeID.setVisible(false);
        jLabelNoticeAge.setVisible(false);
        jLabelNoticeLevel.setVisible(false);
        jLabelNoticeTeam.setVisible(false);
        jLabelNoticePosition.setVisible(false);
        jLabelNoticeTel.setVisible(false);
        jLabelNoticeEmail.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPaneCreate = new javax.swing.JScrollPane();
        jPanelCreate = new javax.swing.JPanel();
        jLabelTitle = new javax.swing.JLabel();
        jLabelName = new javax.swing.JLabel();
        jLabelID = new javax.swing.JLabel();
        jLabelAge = new javax.swing.JLabel();
        jLabelGender = new javax.swing.JLabel();
        jLabelSDate = new javax.swing.JLabel();
        jLabelLevel = new javax.swing.JLabel();
        jLabelTeamInfo = new javax.swing.JLabel();
        jLabelPosition = new javax.swing.JLabel();
        jLabelTel = new javax.swing.JLabel();
        jLabelEmail = new javax.swing.JLabel();
        jLabelPhoto = new javax.swing.JLabel();
        jLabelImageIcon = new javax.swing.JLabel();
        jTextFieldName = new javax.swing.JTextField();
        jTextFieldID = new javax.swing.JTextField();
        jTextFieldAge = new javax.swing.JTextField();
        jComboBoxGender = new javax.swing.JComboBox<>();
        jTextFieldLevel = new javax.swing.JTextField();
        jTextFieldTeamInfo = new javax.swing.JTextField();
        jTextFieldPosition = new javax.swing.JTextField();
        jTextFieldTel = new javax.swing.JTextField();
        jTextFieldEmail = new javax.swing.JTextField();
        jButtonUpload = new javax.swing.JButton();
        jButtonSave = new javax.swing.JButton();
        jComboBoxYear = new javax.swing.JComboBox<>();
        jComboBoxMonth = new javax.swing.JComboBox<>();
        jLabelNoticeName = new javax.swing.JLabel();
        jLabelNoticeID = new javax.swing.JLabel();
        jLabelNoticeAge = new javax.swing.JLabel();
        jLabelNoticeLevel = new javax.swing.JLabel();
        jLabelNoticeTeam = new javax.swing.JLabel();
        jLabelNoticePosition = new javax.swing.JLabel();
        jLabelNoticeTel = new javax.swing.JLabel();
        jLabelNoticeEmail = new javax.swing.JLabel();
        jLabelDomainName = new javax.swing.JLabel();

        jScrollPaneCreate.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jLabelTitle.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabelTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitle.setText("Create Profile");

        jLabelName.setText("Name");

        jLabelID.setText("Employee ID");

        jLabelAge.setText("Age");

        jLabelGender.setText("Gender");

        jLabelSDate.setText("Start Date");

        jLabelLevel.setText("Level");

        jLabelTeamInfo.setText("Team Info");

        jLabelPosition.setText("Position Title");

        jLabelTel.setText("Cell Phone Number");

        jLabelEmail.setText("Email");

        jLabelPhoto.setText("Photo");

        jLabelImageIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelImageIcon.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jTextFieldName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldNameFocusLost(evt);
            }
        });

        jTextFieldID.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldIDFocusLost(evt);
            }
        });

        jTextFieldAge.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldAgeFocusLost(evt);
            }
        });

        jComboBoxGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", "Other" }));

        jTextFieldLevel.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldLevelFocusLost(evt);
            }
        });

        jTextFieldTeamInfo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldTeamInfoFocusLost(evt);
            }
        });

        jTextFieldPosition.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldPositionFocusLost(evt);
            }
        });

        jTextFieldTel.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldTelFocusLost(evt);
            }
        });

        jTextFieldEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldEmailFocusLost(evt);
            }
        });

        jButtonUpload.setText("Upload");
        jButtonUpload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUploadActionPerformed(evt);
            }
        });

        jButtonSave.setText("Save");
        jButtonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveActionPerformed(evt);
            }
        });

        jComboBoxYear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2022", "2021", "2020", "2019", "2018", "2017", "2016", "2015", "2014", "2013", "2012", "2011", "2010", "2009", "2008", "2007", "2006", "2005" }));

        jComboBoxMonth.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));

        jLabelNoticeName.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 8)); // NOI18N
        jLabelNoticeName.setForeground(new java.awt.Color(255, 51, 0));
        jLabelNoticeName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelNoticeName.setText("You must input your name");

        jLabelNoticeID.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 8)); // NOI18N
        jLabelNoticeID.setForeground(new java.awt.Color(255, 51, 0));
        jLabelNoticeID.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelNoticeID.setText("You must input your 6 digits ID correctly");

        jLabelNoticeAge.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 8)); // NOI18N
        jLabelNoticeAge.setForeground(new java.awt.Color(255, 51, 0));
        jLabelNoticeAge.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelNoticeAge.setText("Your age must between 0-99");

        jLabelNoticeLevel.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 8)); // NOI18N
        jLabelNoticeLevel.setForeground(new java.awt.Color(255, 51, 0));
        jLabelNoticeLevel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelNoticeLevel.setText("You must input your level");

        jLabelNoticeTeam.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 8)); // NOI18N
        jLabelNoticeTeam.setForeground(new java.awt.Color(255, 51, 0));
        jLabelNoticeTeam.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelNoticeTeam.setText("You must input your team");

        jLabelNoticePosition.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 8)); // NOI18N
        jLabelNoticePosition.setForeground(new java.awt.Color(255, 51, 0));
        jLabelNoticePosition.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelNoticePosition.setText("You must input your position title");

        jLabelNoticeTel.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 8)); // NOI18N
        jLabelNoticeTel.setForeground(new java.awt.Color(255, 51, 0));
        jLabelNoticeTel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelNoticeTel.setText("You must input your 10 digits phone number");

        jLabelNoticeEmail.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 8)); // NOI18N
        jLabelNoticeEmail.setForeground(new java.awt.Color(255, 51, 0));
        jLabelNoticeEmail.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelNoticeEmail.setText("You must input your email correctly");

        jLabelDomainName.setText("@northeastern.edu");

        javax.swing.GroupLayout jPanelCreateLayout = new javax.swing.GroupLayout(jPanelCreate);
        jPanelCreate.setLayout(jPanelCreateLayout);
        jPanelCreateLayout.setHorizontalGroup(
            jPanelCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCreateLayout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(jPanelCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelID, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelAge, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelGender, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelSDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelLevel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelTeamInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelPosition, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelTel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                    .addComponent(jLabelName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelPhoto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanelCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCreateLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanelCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCreateLayout.createSequentialGroup()
                                .addComponent(jButtonUpload)
                                .addGap(36, 36, 36))
                            .addComponent(jLabelImageIcon, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(103, 103, 103))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCreateLayout.createSequentialGroup()
                        .addGroup(jPanelCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanelCreateLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelNoticeID, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelCreateLayout.createSequentialGroup()
                                .addGap(83, 83, 83)
                                .addGroup(jPanelCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelCreateLayout.createSequentialGroup()
                                        .addComponent(jComboBoxYear, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jComboBoxMonth, 0, 1, Short.MAX_VALUE))
                                    .addComponent(jTextFieldPosition)
                                    .addComponent(jTextFieldTeamInfo)
                                    .addComponent(jTextFieldLevel)
                                    .addComponent(jTextFieldAge)
                                    .addComponent(jTextFieldID)
                                    .addComponent(jTextFieldName)
                                    .addComponent(jTextFieldTel)
                                    .addComponent(jComboBoxGender, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelNoticeName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelNoticeAge, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelNoticeLevel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelNoticeTeam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelNoticePosition, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelNoticeTel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelNoticeEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanelCreateLayout.createSequentialGroup()
                                        .addComponent(jTextFieldEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabelDomainName, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(52, 52, 52))))
            .addComponent(jLabelTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCreateLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonSave, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(233, 233, 233))
        );
        jPanelCreateLayout.setVerticalGroup(
            jPanelCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCreateLayout.createSequentialGroup()
                .addComponent(jLabelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelName)
                    .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addComponent(jLabelNoticeName, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(jPanelCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelID)
                    .addComponent(jTextFieldID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addComponent(jLabelNoticeID)
                .addGap(4, 4, 4)
                .addGroup(jPanelCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelAge)
                    .addComponent(jTextFieldAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addComponent(jLabelNoticeAge, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(jPanelCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelGender)
                    .addComponent(jComboBoxGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSDate)
                    .addComponent(jComboBoxYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelLevel)
                    .addComponent(jTextFieldLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addComponent(jLabelNoticeLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addGroup(jPanelCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTeamInfo)
                    .addComponent(jTextFieldTeamInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addComponent(jLabelNoticeTeam, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addGroup(jPanelCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPosition)
                    .addComponent(jTextFieldPosition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addComponent(jLabelNoticePosition, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addGroup(jPanelCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTel)
                    .addComponent(jTextFieldTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addComponent(jLabelNoticeTel, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addGroup(jPanelCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEmail)
                    .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDomainName))
                .addGap(3, 3, 3)
                .addComponent(jLabelNoticeEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addGroup(jPanelCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelPhoto)
                    .addGroup(jPanelCreateLayout.createSequentialGroup()
                        .addComponent(jLabelImageIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonUpload)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonSave, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jScrollPaneCreate.setViewportView(jPanelCreate);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPaneCreate, javax.swing.GroupLayout.DEFAULT_SIZE, 588, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 465, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPaneCreate, javax.swing.GroupLayout.DEFAULT_SIZE, 453, Short.MAX_VALUE)
                    .addContainerGap()))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonUploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUploadActionPerformed
        // TODO add your handling code here:
        JFileChooser ch = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("图片","png","jpg");
        ch.setFileFilter(filter);

        int ret = ch.showOpenDialog(this);
        if(ret == JFileChooser.APPROVE_OPTION){
            File f = ch.getSelectedFile();
            String fname = f.getAbsolutePath();
            ImageIcon img = new ImageIcon(fname);
            img.setImage(img.getImage().getScaledInstance(121,171,SCALE_DEFAULT));
            jLabelImageIcon.setIcon(img);
        }
    }//GEN-LAST:event_jButtonUploadActionPerformed

    private void jButtonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveActionPerformed
        // TODO add your handling code here:
        if(flag[0] == 0 || flag[1] == 0 || flag[2] == 0 || flag[3] == 0 || flag[4] == 0 || flag[5] == 0 || flag[6] == 0 || flag[7] == 0){
            JOptionPane.showMessageDialog(null, "Some inputs exist error, Please check your inputs", "alert", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        String name = jTextFieldName.getText();
        int id = Integer.parseInt(jTextFieldID.getText());
        int age = Integer.parseInt(jTextFieldAge.getText());
        String gender = (String) jComboBoxGender.getSelectedItem();
        String start_date = ((String) jComboBoxMonth.getSelectedItem()) + ((String) jComboBoxYear.getSelectedItem());
        String position = jTextFieldPosition.getText();
        String team = jTextFieldTeamInfo.getText();
        String level = jTextFieldLevel.getText();
        Long tel = Long.valueOf(jTextFieldTel.getText());
        String email = jTextFieldEmail.getText();
        Icon img = jLabelImageIcon.getIcon();
        
        Info info = pList.addNewProfile();
        info.setName(name);
        info.setAge(age);
        info.setId(id);
        info.setGender(gender);
        info.setStart_date(start_date);
        info.setTeam_info(team);
        info.setLevel(level);
        info.setEmail(email);
        info.setTel(tel);
        info.setPosition_title(position);
        info.setPhoto(img); 
        info.setGenterObject(jComboBoxGender.getSelectedItem());
        info.setMonth(jComboBoxMonth.getSelectedItem());
        info.setYear(jComboBoxYear.getSelectedItem());
     
        JOptionPane.showMessageDialog(this, "New Employee Profile Added");
        
        jTextFieldName.setText("");
        jTextFieldID.setText("");
        jTextFieldAge.setText("");
        jComboBoxGender.setSelectedIndex(0);
        jComboBoxMonth.setSelectedIndex(0);
        jComboBoxYear.setSelectedIndex(0);
        jTextFieldPosition.setText("");
        jTextFieldTeamInfo.setText("");
        jTextFieldLevel.setText("");        
        jTextFieldTel.setText("");        
        jTextFieldEmail.setText("");
        jLabelImageIcon.setIcon(null);
                
    }//GEN-LAST:event_jButtonSaveActionPerformed

    private void jTextFieldNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldNameFocusLost
        // TODO add your handling code here:
        if("".equals(jTextFieldName.getText())){
            jLabelNoticeName.setVisible(true);
            flag[0] = 0;
        }
        else{
            jLabelNoticeName.setVisible(false);
            flag[0] = 1;
        }
        
    }//GEN-LAST:event_jTextFieldNameFocusLost

    private void jTextFieldIDFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldIDFocusLost
        // TODO add your handling code here:
        if(jTextFieldID.getText().matches("\\d{6}") == false){
            jLabelNoticeID.setVisible(true);
            flag[1] = 0;
        }
        else{
            jLabelNoticeID.setVisible(false);            
            flag[1] = 1;
        }
        
    }//GEN-LAST:event_jTextFieldIDFocusLost

    private void jTextFieldAgeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldAgeFocusLost
        // TODO add your handling code here:
        if(jTextFieldAge.getText().matches("\\d{2}") == false){
            jLabelNoticeAge.setVisible(true);
            flag[2] = 0;
        }
        else{
            jLabelNoticeAge.setVisible(false);
            flag[2] = 1;
        }
        
        
    }//GEN-LAST:event_jTextFieldAgeFocusLost

    private void jTextFieldLevelFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldLevelFocusLost
        // TODO add your handling code here:
        if("".equals(jTextFieldLevel.getText())){
            jLabelNoticeLevel.setVisible(true);
            flag[3] = 0;
        }
        else{
            jLabelNoticeLevel.setVisible(false);
            flag[3] = 1;
        }
    }//GEN-LAST:event_jTextFieldLevelFocusLost

    private void jTextFieldTeamInfoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldTeamInfoFocusLost
        // TODO add your handling code here:
        if("".equals(jTextFieldTeamInfo.getText())){
            jLabelNoticeTeam.setVisible(true);
            flag[4] = 0;
        }
        else{
            jLabelNoticeTeam.setVisible(false);
            flag[4] = 1;
        }
        
    }//GEN-LAST:event_jTextFieldTeamInfoFocusLost

    private void jTextFieldPositionFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldPositionFocusLost
        // TODO add your handling code here:
        if("".equals(jTextFieldPosition.getText())){
            jLabelNoticePosition.setVisible(true);
            flag[5] = 0;
        }
        else{
            jLabelNoticePosition.setVisible(false);
            flag[5] = 1;
        }
        
    }//GEN-LAST:event_jTextFieldPositionFocusLost

    private void jTextFieldTelFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldTelFocusLost
        // TODO add your handling code here:
        if(jTextFieldTel.getText().matches("\\d{10}") == false){
            jLabelNoticeTel.setVisible(true);
            flag[6] = 0;
        }
        else{
            jLabelNoticeTel.setVisible(false);
            flag[6] = 1;
            
        }
    }//GEN-LAST:event_jTextFieldTelFocusLost

    private void jTextFieldEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldEmailFocusLost
        // TODO add your handling code here:
        if("".equals(jTextFieldEmail.getText())){
            jLabelNoticeEmail.setVisible(true);
            flag[7] = 0;
        }
        else{
            jLabelNoticeEmail.setVisible(false);
            flag[7] = 1;
            
        }
        
    }//GEN-LAST:event_jTextFieldEmailFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSave;
    private javax.swing.JButton jButtonUpload;
    private javax.swing.JComboBox<String> jComboBoxGender;
    private javax.swing.JComboBox<String> jComboBoxMonth;
    private javax.swing.JComboBox<String> jComboBoxYear;
    private javax.swing.JLabel jLabelAge;
    private javax.swing.JLabel jLabelDomainName;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelGender;
    private javax.swing.JLabel jLabelID;
    private javax.swing.JLabel jLabelImageIcon;
    private javax.swing.JLabel jLabelLevel;
    private javax.swing.JLabel jLabelName;
    private javax.swing.JLabel jLabelNoticeAge;
    private javax.swing.JLabel jLabelNoticeEmail;
    private javax.swing.JLabel jLabelNoticeID;
    private javax.swing.JLabel jLabelNoticeLevel;
    private javax.swing.JLabel jLabelNoticeName;
    private javax.swing.JLabel jLabelNoticePosition;
    private javax.swing.JLabel jLabelNoticeTeam;
    private javax.swing.JLabel jLabelNoticeTel;
    private javax.swing.JLabel jLabelPhoto;
    private javax.swing.JLabel jLabelPosition;
    private javax.swing.JLabel jLabelSDate;
    private javax.swing.JLabel jLabelTeamInfo;
    private javax.swing.JLabel jLabelTel;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JPanel jPanelCreate;
    private javax.swing.JScrollPane jScrollPaneCreate;
    private javax.swing.JTextField jTextFieldAge;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldID;
    private javax.swing.JTextField jTextFieldLevel;
    private javax.swing.JTextField jTextFieldName;
    private javax.swing.JTextField jTextFieldPosition;
    private javax.swing.JTextField jTextFieldTeamInfo;
    private javax.swing.JTextField jTextFieldTel;
    // End of variables declaration//GEN-END:variables
}
