/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import model.Info;

/**
 *
 * @author ZeyuLiao
 */
public class DetailPanel extends javax.swing.JPanel {

    /**
     * Creates new form DetailPanel
     * @param info
     */
    public DetailPanel(Info info) {
        initComponents();
        jLabelName.setText("Name: " +String.valueOf( info.getName()));
        jLabelID.setText("ID: "+ String.valueOf(info.getId()));
        jLabelAge.setText("Age: "+ String.valueOf(info.getAge()));
        jLabelGender.setText("Gender: "+ String.valueOf(info.getGender()));
        jLabelSDate.setText("Start Date: "+ String.valueOf(info.getStart_date()));
        jLabelLevel.setText("Level: "+ String.valueOf(info.getLevel()));
        jLabelPosition.setText("Position Title: "+ String.valueOf(info.getPosition_title()));
        jLabelTeamInfo.setText("Team: "+ String.valueOf(info.getTeam_info()));
        jLabelTel.setText("Phone Number: "+ String.valueOf(info.getTel()));
        jLabelEmail.setText("Email: "+ String.valueOf(info.getEmail()) + "@northeastern.edu");
        jLabelImageIcon.setIcon(info.getPhoto());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelName = new javax.swing.JLabel();
        jLabelID = new javax.swing.JLabel();
        jLabelAge = new javax.swing.JLabel();
        jLabelGender = new javax.swing.JLabel();
        jLabelSDate = new javax.swing.JLabel();
        jLabelLevel = new javax.swing.JLabel();
        jLabelTeamInfo = new javax.swing.JLabel();
        jLabelPosition = new javax.swing.JLabel();
        jLabelTel = new javax.swing.JLabel();
        jLabelEmail = new javax.swing.JLabel();
        jLabelImageIcon = new javax.swing.JLabel();

        jLabelName.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabelName.setText("Name");

        jLabelID.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabelID.setText("Employee ID");

        jLabelAge.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabelAge.setText("Age");

        jLabelGender.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabelGender.setText("Gender");

        jLabelSDate.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabelSDate.setText("Start Date");

        jLabelLevel.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabelLevel.setText("Level");

        jLabelTeamInfo.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabelTeamInfo.setText("Team Info");

        jLabelPosition.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabelPosition.setText("Position Title");

        jLabelTel.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabelTel.setText("Cell Phone Number");

        jLabelEmail.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabelEmail.setText("Email");

        jLabelImageIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelImageIcon.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelImageIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelTel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelID, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelGender, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabelName, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabelAge, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabelEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelTeamInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelPosition, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelSDate, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelImageIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelName)
                            .addComponent(jLabelAge))
                        .addGap(18, 18, 18)
                        .addComponent(jLabelID)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelGender)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelTel)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelEmail)))
                .addGap(18, 18, 18)
                .addComponent(jLabelTeamInfo)
                .addGap(18, 18, 18)
                .addComponent(jLabelPosition)
                .addGap(18, 18, 18)
                .addComponent(jLabelLevel)
                .addGap(18, 18, 18)
                .addComponent(jLabelSDate)
                .addContainerGap(15, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelAge;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelGender;
    private javax.swing.JLabel jLabelID;
    private javax.swing.JLabel jLabelImageIcon;
    private javax.swing.JLabel jLabelLevel;
    private javax.swing.JLabel jLabelName;
    private javax.swing.JLabel jLabelPosition;
    private javax.swing.JLabel jLabelSDate;
    private javax.swing.JLabel jLabelTeamInfo;
    private javax.swing.JLabel jLabelTel;
    // End of variables declaration//GEN-END:variables
}
