/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Info;
import model.ProfileList;

/**
 *
 * @author ZeyuLiao
 */
public class ViewPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreatePanel
     */
    ProfileList pList;

    public ViewPanel(ProfileList pList) {
        this.pList = pList;
            
        initComponents();
        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPaneView = new javax.swing.JScrollPane();
        jPanelView = new javax.swing.JPanel();
        jScrollPaneViewAll = new javax.swing.JScrollPane();
        jTableViewAll = new javax.swing.JTable();
        jLabelTitle = new javax.swing.JLabel();
        jSplitPane1 = new javax.swing.JSplitPane();
        jPanelButtonGroup = new javax.swing.JPanel();
        jButtonViewProfile = new javax.swing.JButton();
        jButtonUpdateProfile = new javax.swing.JButton();
        jButtonDeleteProfile = new javax.swing.JButton();
        jButtonSearchProfile = new javax.swing.JButton();
        jButtonRefresh = new javax.swing.JButton();
        jPanelViewDisplay = new javax.swing.JPanel();
        jLabelName = new javax.swing.JLabel();
        jLabelID = new javax.swing.JLabel();
        jLabelAge = new javax.swing.JLabel();
        jLabelGender = new javax.swing.JLabel();
        jLabelSDate = new javax.swing.JLabel();
        jLabelLevel = new javax.swing.JLabel();
        jLabelTeamInfo = new javax.swing.JLabel();
        jLabelPosition = new javax.swing.JLabel();
        jLabelTel = new javax.swing.JLabel();
        jLabelEmail = new javax.swing.JLabel();
        jLabelImageIcon = new javax.swing.JLabel();

        jScrollPaneView.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jTableViewAll.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Name", "ID", "Team", "Position", "Title"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPaneViewAll.setViewportView(jTableViewAll);

        jLabelTitle.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabelTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitle.setText("ViewProfile");

        jSplitPane1.setDividerLocation(40);
        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        jButtonViewProfile.setText("View Details");
        jButtonViewProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonViewProfileActionPerformed(evt);
            }
        });

        jButtonUpdateProfile.setText("Update Profile");
        jButtonUpdateProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdateProfileActionPerformed(evt);
            }
        });

        jButtonDeleteProfile.setText("Delete Profile");
        jButtonDeleteProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteProfileActionPerformed(evt);
            }
        });

        jButtonSearchProfile.setText("Search Profile");

        jButtonRefresh.setText("Refresh");
        jButtonRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRefreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelButtonGroupLayout = new javax.swing.GroupLayout(jPanelButtonGroup);
        jPanelButtonGroup.setLayout(jPanelButtonGroupLayout);
        jPanelButtonGroupLayout.setHorizontalGroup(
            jPanelButtonGroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelButtonGroupLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonRefresh)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 147, Short.MAX_VALUE)
                .addComponent(jButtonViewProfile)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonUpdateProfile)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonDeleteProfile)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonSearchProfile)
                .addGap(33, 33, 33))
        );
        jPanelButtonGroupLayout.setVerticalGroup(
            jPanelButtonGroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelButtonGroupLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelButtonGroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonViewProfile)
                    .addComponent(jButtonUpdateProfile)
                    .addComponent(jButtonDeleteProfile)
                    .addComponent(jButtonSearchProfile)
                    .addComponent(jButtonRefresh))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(jPanelButtonGroup);

        jLabelName.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabelName.setText("Name");

        jLabelID.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabelID.setText("Employee ID");

        jLabelAge.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabelAge.setText("Age");

        jLabelGender.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabelGender.setText("Gender");

        jLabelSDate.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabelSDate.setText("Start Date");

        jLabelLevel.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabelLevel.setText("Level");

        jLabelTeamInfo.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabelTeamInfo.setText("Team Info");

        jLabelPosition.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabelPosition.setText("Position Title");

        jLabelTel.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabelTel.setText("Cell Phone Number");

        jLabelEmail.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabelEmail.setText("Email");

        jLabelImageIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelImageIcon.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        javax.swing.GroupLayout jPanelViewDisplayLayout = new javax.swing.GroupLayout(jPanelViewDisplay);
        jPanelViewDisplay.setLayout(jPanelViewDisplayLayout);
        jPanelViewDisplayLayout.setHorizontalGroup(
            jPanelViewDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelViewDisplayLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelViewDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelViewDisplayLayout.createSequentialGroup()
                        .addComponent(jLabelImageIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanelViewDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelTel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanelViewDisplayLayout.createSequentialGroup()
                                .addGroup(jPanelViewDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelID, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelGender, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanelViewDisplayLayout.createSequentialGroup()
                                        .addComponent(jLabelName, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabelAge, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabelEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 81, Short.MAX_VALUE))))
                    .addGroup(jPanelViewDisplayLayout.createSequentialGroup()
                        .addGroup(jPanelViewDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelTeamInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelPosition, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelSDate, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelViewDisplayLayout.setVerticalGroup(
            jPanelViewDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelViewDisplayLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelViewDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelImageIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelViewDisplayLayout.createSequentialGroup()
                        .addGroup(jPanelViewDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelName)
                            .addComponent(jLabelAge))
                        .addGap(18, 18, 18)
                        .addComponent(jLabelID)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelGender)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelTel)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelEmail)))
                .addGap(18, 18, 18)
                .addComponent(jLabelTeamInfo)
                .addGap(31, 31, 31)
                .addComponent(jLabelPosition)
                .addGap(36, 36, 36)
                .addComponent(jLabelLevel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(jLabelSDate)
                .addGap(26, 26, 26))
        );

        jSplitPane1.setRightComponent(jPanelViewDisplay);

        javax.swing.GroupLayout jPanelViewLayout = new javax.swing.GroupLayout(jPanelView);
        jPanelView.setLayout(jPanelViewLayout);
        jPanelViewLayout.setHorizontalGroup(
            jPanelViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelViewLayout.createSequentialGroup()
                .addGroup(jPanelViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelViewLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPaneViewAll))
                    .addComponent(jSplitPane1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
            .addGroup(jPanelViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelViewLayout.createSequentialGroup()
                    .addGap(73, 73, 73)
                    .addComponent(jLabelTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 564, Short.MAX_VALUE)
                    .addGap(74, 74, 74)))
        );
        jPanelViewLayout.setVerticalGroup(
            jPanelViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelViewLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jScrollPaneViewAll, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 453, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanelViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelViewLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabelTitle)
                    .addContainerGap(607, Short.MAX_VALUE)))
        );

        jScrollPaneView.setViewportView(jPanelView);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPaneView, javax.swing.GroupLayout.DEFAULT_SIZE, 712, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPaneView)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonDeleteProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteProfileActionPerformed
        // TODO add your handling code here:
        int selectRowIndex = jTableViewAll.getSelectedRow();
        if(selectRowIndex <0){
            JOptionPane.showMessageDialog(this,"Please select a row to delete");
            return;
        }
        
        DefaultTableModel model = (DefaultTableModel) jTableViewAll.getModel();
        Info selectInfo = (Info) model.getValueAt(selectRowIndex ,0 );
        pList.deleteProfiles(selectInfo);
        JOptionPane.showMessageDialog(this,"Profile deleted");
        
        populateTable();
       
    }//GEN-LAST:event_jButtonDeleteProfileActionPerformed

    private void jButtonViewProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonViewProfileActionPerformed
        // TODO add your handling code here:
        jSplitPane1.setBottomComponent(jPanelViewDisplay);       
        int selectRowIndex = jTableViewAll.getSelectedRow();
        if(selectRowIndex <0){
            JOptionPane.showMessageDialog(this,"Please select a row to delete");
            return;
        }
        
        DefaultTableModel model = (DefaultTableModel) jTableViewAll.getModel();
        Info selectInfo = (Info) model.getValueAt(selectRowIndex ,0 );
        
        jLabelName.setText("Name: " +String.valueOf( selectInfo.getName()));
        jLabelID.setText("ID: "+ String.valueOf(selectInfo.getId()));
        jLabelAge.setText("Age: "+ String.valueOf(selectInfo.getAge()));
        jLabelGender.setText("Gender: "+ String.valueOf(selectInfo.getGender()));
        jLabelSDate.setText("Start Date: "+ String.valueOf(selectInfo.getStart_date()));
        jLabelLevel.setText("Level: "+ String.valueOf(selectInfo.getLevel()));
        jLabelPosition.setText("Position Title: "+ String.valueOf(selectInfo.getPosition_title()));
        jLabelTeamInfo.setText("Team: "+ String.valueOf(selectInfo.getTeam_info()));
        jLabelTel.setText("Phone Number: "+ String.valueOf(selectInfo.getTel()));
        jLabelEmail.setText("Email: "+ String.valueOf(selectInfo.getEmail()) + "@northeastern.edu");
        jLabelImageIcon.setIcon(selectInfo.getPhoto());
        
        
        
        
    }//GEN-LAST:event_jButtonViewProfileActionPerformed

    private void jButtonUpdateProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateProfileActionPerformed
        // TODO add your handling code here:
        
        int selectRowIndex = jTableViewAll.getSelectedRow();
        if(selectRowIndex <0){
            JOptionPane.showMessageDialog(this,"Please select a row to delete");
            return;
        }
        DefaultTableModel model = (DefaultTableModel) jTableViewAll.getModel();
        Info selectInfo = (Info) model.getValueAt(selectRowIndex ,0 );
        
        UpdatePanel ep = new UpdatePanel(selectInfo, pList);
        jSplitPane1.setBottomComponent(ep);
        populateTable();
        
        
        
        
        
        
        
    }//GEN-LAST:event_jButtonUpdateProfileActionPerformed

    private void jButtonRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRefreshActionPerformed
        // TODO add your handling code here:
        populateTable();
    }//GEN-LAST:event_jButtonRefreshActionPerformed

    private void populateTable(){
        DefaultTableModel model = (DefaultTableModel) jTableViewAll.getModel();
        model.setRowCount(0);
        
        for (Info info : pList.getHistory()){
            Object[] row = new Object[5];          
            row[0] = info;
            row[1] = info.getId();
            row[2] = info.getTeam_info();
            row[3] = info.getPosition_title();
            row[4] = info.getLevel();
            
            model.addRow(row);           
        }
        
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDeleteProfile;
    private javax.swing.JButton jButtonRefresh;
    private javax.swing.JButton jButtonSearchProfile;
    private javax.swing.JButton jButtonUpdateProfile;
    private javax.swing.JButton jButtonViewProfile;
    private javax.swing.JLabel jLabelAge;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelGender;
    private javax.swing.JLabel jLabelID;
    private javax.swing.JLabel jLabelImageIcon;
    private javax.swing.JLabel jLabelLevel;
    private javax.swing.JLabel jLabelName;
    private javax.swing.JLabel jLabelPosition;
    private javax.swing.JLabel jLabelSDate;
    private javax.swing.JLabel jLabelTeamInfo;
    private javax.swing.JLabel jLabelTel;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JPanel jPanelButtonGroup;
    private javax.swing.JPanel jPanelView;
    private javax.swing.JPanel jPanelViewDisplay;
    private javax.swing.JScrollPane jScrollPaneView;
    private javax.swing.JScrollPane jScrollPaneViewAll;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTable jTableViewAll;
    // End of variables declaration//GEN-END:variables
}
